x_cp_ns: &cp_ns
  node-role.kubernetes.io/control-plane: ""
x_cp_tol: &cp_tol
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
gateway:
  nodeSelector: *cp_ns
  tolerations: *cp_tol
backend:
  nodeSelector: *cp_ns
  tolerations: *cp_tol
read:
  nodeSelector: *cp_ns
  tolerations: *cp_tol
write:
  nodeSelector: *cp_ns
  tolerations: *cp_tol
