x_cp_affinity: &cp_affinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
x_cp_tol: &cp_tol
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

query:
  affinity: *cp_affinity
  tolerations: *cp_tol
storegateway:
  affinity: *cp_affinity
  tolerations: *cp_tol
